-- RFC1 - Histórico de servicios de un usuario
-- Versión con nivel de aislamiento SERIALIZABLE
-- Incluye una pausa de 30 segundos entre consultas para observar bloqueos y errores ORA-08177

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

-- Primera ejecución
SELECT
  s.ID AS SOLICITUD_ID,
  v.ID AS VIAJE_ID,
  s.SOLICITADO_EN,
  v.INICIO,
  v.FIN,
  s.TIPO AS SERVICIO,
  s.NIVEL,
  s.DISTANCIA_KM AS DISTANCIA_ESTIMADA_KM,
  v.DISTANCIA_KM AS DISTANCIA_REAL_KM,
  s.TARIFA_CALCULADA AS VALOR_PREVISTO,
  v.COSTO_TOTAL,
  ROUND(0.6 * NVL(v.COSTO_TOTAL, 0), 2) AS COMISION_CONDUCTOR,
  ucond.NOMBRE AS CONDUCTOR,
  veh.PLACA,
  (veh.MARCA || ' ' || veh.MODELO) AS VEHICULO,
  origen.NOMBRE AS ORIGEN_NOMBRE,
  origen.DIRECCION AS ORIGEN_DIRECCION,
  destino.NOMBRE AS DESTINO_NOMBRE,
  destino.DIRECCION AS DESTINO_DIRECCION,
  s.ESTADO
FROM SOLICITUD_SERVICIO s
JOIN USUARIO_CLIENTE uc ON uc.ID_USUARIO = s.ID_USUARIO
LEFT JOIN VIAJE v ON v.ID_SOLICITUD = s.ID
LEFT JOIN USUARIO ucond ON ucond.ID = v.ID_CONDUCTOR
LEFT JOIN VEHICULO veh ON veh.ID = v.ID_VEHICULO
LEFT JOIN (
    SELECT ps.ID_SOLICITUD, p.NOMBRE, p.DIRECCION
    FROM PARADA_SERVICIO ps
    JOIN PUNTO_GEOGRAFICO p ON p.ID = ps.ID_PUNTO
    WHERE ps.TIPO_PARADA = 'INICIO'
) origen ON origen.ID_SOLICITUD = s.ID
LEFT JOIN (
    SELECT ps.ID_SOLICITUD, p.NOMBRE, p.DIRECCION
    FROM PARADA_SERVICIO ps
    JOIN PUNTO_GEOGRAFICO p ON p.ID = ps.ID_PUNTO
    WHERE ps.TIPO_PARADA = 'DESTINO'
) destino ON destino.ID_SOLICITUD = s.ID
WHERE uc.ID_USUARIO = :clienteId
ORDER BY s.SOLICITADO_EN DESC, v.INICIO DESC NULLS LAST;

-- Pausa de 30 segundos (permite ver bloqueos o fallas ORA-08177)
BEGIN
    DBMS_LOCK.SLEEP(30);
END;
/

-- Segunda ejecución
SELECT
  s.ID AS SOLICITUD_ID,
  v.ID AS VIAJE_ID,
  s.SOLICITADO_EN,
  v.INICIO,
  v.FIN,
  s.TIPO AS SERVICIO,
  s.NIVEL,
  s.DISTANCIA_KM AS DISTANCIA_ESTIMADA_KM,
  v.DISTANCIA_KM AS DISTANCIA_REAL_KM,
  s.TARIFA_CALCULADA AS VALOR_PREVISTO,
  v.COSTO_TOTAL,
  ROUND(0.6 * NVL(v.COSTO_TOTAL, 0), 2) AS COMISION_CONDUCTOR,
  ucond.NOMBRE AS CONDUCTOR,
  veh.PLACA,
  (veh.MARCA || ' ' || veh.MODELO) AS VEHICULO,
  origen.NOMBRE AS ORIGEN_NOMBRE,
  origen.DIRECCION AS ORIGEN_DIRECCION,
  destino.NOMBRE AS DESTINO_NOMBRE,
  destino.DIRECCION AS DESTINO_DIRECCION,
  s.ESTADO
FROM SOLICITUD_SERVICIO s
JOIN USUARIO_CLIENTE uc ON uc.ID_USUARIO = s.ID_USUARIO
LEFT JOIN VIAJE v ON v.ID_SOLICITUD = s.ID
LEFT JOIN USUARIO ucond ON ucond.ID = v.ID_CONDUCTOR
LEFT JOIN VEHICULO veh ON veh.ID = v.ID_VEHICULO
LEFT JOIN (
    SELECT ps.ID_SOLICITUD, p.NOMBRE, p.DIRECCION
    FROM PARADA_SERVICIO ps
    JOIN PUNTO_GEOGRAFICO p ON p.ID = ps.ID_PUNTO
    WHERE ps.TIPO_PARADA = 'INICIO'
) origen ON origen.ID_SOLICITUD = s.ID
LEFT JOIN (
    SELECT ps.ID_SOLICITUD, p.NOMBRE, p.DIRECCION
    FROM PARADA_SERVICIO ps
    JOIN PUNTO_GEOGRAFICO p ON p.ID = ps.ID_PUNTO
    WHERE ps.TIPO_PARADA = 'DESTINO'
) destino ON destino.ID_SOLICITUD = s.ID
WHERE uc.ID_USUARIO = :clienteId
ORDER BY s.SOLICITADO_EN DESC, v.INICIO DESC NULLS LAST;

COMMIT;
